import "dotenv/config";
import { eq } from "drizzle-orm";
import { drizzle } from "drizzle-orm/mysql2";
import { robots } from "./drizzle/schema.js";

const db = drizzle(process.env.DATABASE_URL);

const sampleRobots = [
  {
    name: "MiR250 Hook",
    manufacturer: "Mobile Industrial Robots",
    type: "mobile_base",
    length: 890,
    width: 580,
    height: 322,
    weight: 67,
    usablePayload: 250,
    functions: "Autonomous material transport, hook-based cart pulling",
    reach: null,
    driveSystem: "Differential drive",
    certifications: "ISO 3691-4, CE",
    rosCompatible: 1,
    rosDistros: "Noetic, Humble",
    sdkAvailable: 1,
    apiAvailable: 1,
    operationTime: 540,
    batteryLife: 540,
    maxSpeed: 2000,
    forceSensor: 0,
    eoatCompatibility: null,
    armPayload: null,
    armReach: null,
    armDof: null,
    websiteUrl: "https://www.mobile-industrial-robots.com/solutions/robots/mir250-hook/",
    remarks: "Ideal for logistics and warehouse automation",
  },
  {
    name: "UR10e",
    manufacturer: "Universal Robots",
    type: "manipulator_arm",
    length: null,
    width: null,
    height: null,
    weight: 33,
    usablePayload: null,
    functions: "Pick and place, machine tending, packaging",
    reach: 1300,
    driveSystem: null,
    certifications: "ISO 10218-1, CE",
    rosCompatible: 1,
    rosDistros: "Noetic, Humble, Jazzy",
    sdkAvailable: 1,
    apiAvailable: 1,
    operationTime: null,
    batteryLife: null,
    maxSpeed: null,
    forceSensor: 1,
    eoatCompatibility: "Gripper, Suction Cup, Custom EOAT",
    armPayload: 10,
    armReach: 1300,
    armDof: 6,
    websiteUrl: "https://www.universal-robots.com/products/ur10-robot/",
    remarks: "Collaborative robot with built-in force/torque sensor",
  },
  {
    name: "Fetch Mobile Manipulator",
    manufacturer: "Fetch Robotics",
    type: "mobile_manipulator",
    length: 660,
    width: 660,
    height: 1420,
    weight: 113,
    usablePayload: 25,
    functions: "Mobile manipulation, research, warehouse automation",
    reach: 800,
    driveSystem: "Differential drive",
    certifications: "CE, FCC",
    rosCompatible: 1,
    rosDistros: "Melodic, Noetic",
    sdkAvailable: 1,
    apiAvailable: 1,
    operationTime: 480,
    batteryLife: 480,
    maxSpeed: 1000,
    forceSensor: 0,
    eoatCompatibility: "Parallel Gripper",
    armPayload: 6,
    armReach: 800,
    armDof: 7,
    websiteUrl: "https://fetchrobotics.com/robotics-platforms/mobile-manipulator/",
    remarks: "Integrated mobile base and arm for research and industrial use",
  },
  {
    name: "KUKA KMR iiwa",
    manufacturer: "KUKA",
    type: "mobile_manipulator",
    length: 800,
    width: 600,
    height: 1800,
    weight: 220,
    usablePayload: 30,
    functions: "Flexible manufacturing, assembly, quality inspection",
    reach: 800,
    driveSystem: "Omnidirectional",
    certifications: "ISO 10218-1, ISO 3691-4, Cleanroom Class 5",
    rosCompatible: 0,
    rosDistros: null,
    sdkAvailable: 1,
    apiAvailable: 1,
    operationTime: 360,
    batteryLife: 360,
    maxSpeed: 1200,
    forceSensor: 1,
    eoatCompatibility: "Gripper, Suction Cup, Welding Tool",
    armPayload: 14,
    armReach: 800,
    armDof: 7,
    websiteUrl: "https://www.kuka.com/en-us/products/mobility/mobile-robots/kmr-iiwa",
    remarks: "Sensitive collaborative robot on mobile platform, cleanroom compatible",
  },
  {
    name: "TurtleBot 4",
    manufacturer: "Clearpath Robotics",
    type: "mobile_base",
    length: 342,
    width: 339,
    height: 351,
    weight: 9,
    usablePayload: 15,
    functions: "Research, education, SLAM, navigation",
    reach: null,
    driveSystem: "Differential drive",
    certifications: "CE, FCC",
    rosCompatible: 1,
    rosDistros: "Humble, Iron",
    sdkAvailable: 1,
    apiAvailable: 1,
    operationTime: 240,
    batteryLife: 240,
    maxSpeed: 500,
    forceSensor: 0,
    eoatCompatibility: null,
    armPayload: null,
    armReach: null,
    armDof: null,
    websiteUrl: "https://clearpathrobotics.com/turtlebot-4/",
    remarks: "Popular research and education platform with ROS 2 support",
  },
  {
    name: "ABB IRB 1200",
    manufacturer: "ABB",
    type: "manipulator_arm",
    length: null,
    width: null,
    height: null,
    weight: 52,
    usablePayload: null,
    functions: "Assembly, material handling, machine tending",
    reach: 900,
    driveSystem: null,
    certifications: "ISO 10218-1, CE",
    rosCompatible: 0,
    rosDistros: null,
    sdkAvailable: 1,
    apiAvailable: 1,
    operationTime: null,
    batteryLife: null,
    maxSpeed: null,
    forceSensor: 0,
    eoatCompatibility: "Gripper, Vacuum, Custom",
    armPayload: 7,
    armReach: 900,
    armDof: 6,
    websiteUrl: "https://new.abb.com/products/robotics/industrial-robots/irb-1200",
    remarks: "Compact industrial robot for small parts assembly",
  },
  {
    name: "Franka Emika Panda",
    manufacturer: "Franka Emika",
    type: "manipulator_arm",
    length: null,
    width: null,
    height: null,
    weight: 18,
    usablePayload: null,
    functions: "Research, sensitive manipulation, assembly",
    reach: 855,
    driveSystem: null,
    certifications: "CE",
    rosCompatible: 1,
    rosDistros: "Noetic, Humble",
    sdkAvailable: 1,
    apiAvailable: 1,
    operationTime: null,
    batteryLife: null,
    maxSpeed: null,
    forceSensor: 1,
    eoatCompatibility: "Gripper, Custom EOAT",
    armPayload: 3,
    armReach: 855,
    armDof: 7,
    websiteUrl: "https://www.franka.de/robot-system",
    remarks: "Research-grade collaborative robot with integrated torque sensors in all joints",
  },
  {
    name: "Clearpath Ridgeback",
    manufacturer: "Clearpath Robotics",
    type: "mobile_base",
    length: 960,
    width: 823,
    height: 410,
    weight: 145,
    usablePayload: 100,
    functions: "Heavy payload transport, research platform",
    reach: null,
    driveSystem: "Omnidirectional (Mecanum wheels)",
    certifications: "CE, FCC",
    rosCompatible: 1,
    rosDistros: "Noetic, Humble",
    sdkAvailable: 1,
    apiAvailable: 1,
    operationTime: 480,
    batteryLife: 480,
    maxSpeed: 1100,
    forceSensor: 0,
    eoatCompatibility: null,
    armPayload: null,
    armReach: null,
    armDof: null,
    websiteUrl: "https://clearpathrobotics.com/ridgeback-indoor-robot-platform/",
    remarks: "Heavy-duty omnidirectional mobile base for research and industrial applications",
  },

  // ===== Humanoid robots (ported from the Humanoid dashboard) =====
  {
    name: "AlphaBOT2",
    manufacturer: "AI² Robotics",
    type: "humanoid",
    country: "China",
    year: 2025,
    heightCm: null,
    heightNote: "Not disclosed (reaches up to 240 cm)",
    weight: null,
    locomotion: "Wheeled base + lifting mechanism",
    maxSpeedKmh: null,
    batteryHours: 6,
    batteryNote: "6+ hours continuous",
    ipRating: null,
    priceUsd: "Not disclosed (enterprise)",
    dofTotal: 34,
    dofNote: "34+ DOF",
    dofBase: "Wheeled (DOF not specified)",
    payloadPerArm: 5,
    payloadNote: "5 kg per arm",
    cpu: "Proprietary AI processors",
    gpu: "Proprietary AI accelerator",
    memory: "Not disclosed",
    aiCompute: "Not disclosed",
    os: "Not disclosed",
    sensors: ["Multi-camera 360° vision", "Force/torque sensors", "Microphone arrays", "Environmental sensors"],
    connectivity: ["Wi-Fi", "Ethernet", "OTA updates"],
    rosCompatible: 0,
    ros2Support: "none",
    ros2Note: "No public ROS2 driver found",
    sdkAvailable: 0,
    sdkLanguages: [],
    simulationSupport: [],
    sdkLinks: [
      { label: "Official Website", url: "https://ai2robotics.com/en/", type: "website" },
      { label: "FiS-VLA Model (open-source)", url: "https://fast-in-slow.github.io/", type: "docs" },
    ],
    llmIntegration: 1,
    openSource: 0,
    aiPlatform: "AlphaBrain (proprietary)",
    openSourceModel: "FiS-VLA (Fast-in-Slow) — open-source VLA model",
    scoreSdkOpenness: 1,
    scoreRos2Support: 1,
    scoreComputePower: 3,
    scoreSimulationSupport: 1,
    scoreDeveloperCommunity: 2,
    scorePayloadCapability: 3,
    scoreDexterity: 3,
    scoreResearchOverall: 2,
    summary:
      "Industrial-focused humanoid with 34+ DOF and a wheeled lifting mechanism reaching up to 240 cm. Deployed in automotive and semiconductor manufacturing. The AlphaBrain platform powers its GOVLA model.",
    researchNote:
      "Closed-source SDK and no public ROS2 driver make independent software development challenging. The open-source FiS-VLA model is a valuable research contribution, but low-level robot control remains proprietary.",
    recommendation: "not-recommended",
    websiteUrl: "https://ai2robotics.com/en/",
  },
  {
    name: "Galbot G1",
    manufacturer: "Galaxy General Robotics",
    type: "humanoid",
    country: "China",
    year: 2024,
    heightCm: 173,
    weight: 85,
    locomotion: "Wheeled base + torso lift (65 cm range)",
    maxSpeedKmh: 7.2,
    batteryHours: 10,
    ipRating: null,
    priceUsd: "$50,000 – $75,000",
    dofTotal: 26,
    dofBase: "Wheeled",
    payloadPerArm: 5,
    payloadNote: "5 kg per arm; 10 kg combined dual-arm",
    cpu: "14-core CPU (Thor) / 8-core CPU (Standard)",
    gpu: "NVIDIA Jetson AGX Thor — 2,560-core Blackwell GPU",
    memory: "128 GB (Thor variant)",
    aiCompute: "2,070 FP4 TFLOPS (Thor)",
    os: "Not disclosed",
    sensors: [
      "Head depth camera ×1",
      "Head fisheye cameras ×2",
      "Wrist depth cameras ×2",
      "6-axis force/torque sensor (wrist)",
      "4-microphone array",
      "Tactile sensors (hands)",
    ],
    connectivity: ["Wi-Fi", "Bluetooth", "4G/5G", "Cloud integration"],
    rosCompatible: 0,
    ros2Support: "not-confirmed",
    ros2Note: "SDK uses C++/Python directly; ROS2 integration not officially confirmed in public docs",
    sdkAvailable: 1,
    sdkLanguages: ["C++", "Python"],
    simulationSupport: ["NVIDIA Isaac (OpenWBT_Isaac)"],
    sdkLinks: [
      { label: "Official Website", url: "https://www.galbot.com/g1", type: "website" },
      { label: "GalbotSDK (GitHub)", url: "https://github.com/GalaxyGeneralRobotics/GalbotSDK", type: "github" },
      { label: "OpenWBT Teleoperation", url: "https://github.com/GalaxyGeneralRobotics/OpenWBT", type: "github" },
    ],
    llmIntegration: 1,
    openSource: 0,
    aiPlatform: "Proprietary embodied AI platform; Sim2Real methodology",
    openSourceModel: null,
    scoreSdkOpenness: 3,
    scoreRos2Support: 2,
    scoreComputePower: 5,
    scoreSimulationSupport: 3,
    scoreDeveloperCommunity: 3,
    scorePayloadCapability: 3,
    scoreDexterity: 3,
    scoreResearchOverall: 3,
    summary:
      "Commercial-grade mobile dual-arm robot with 26 DOF and a torso lift mechanism. The Premium variant features the NVIDIA Jetson AGX Thor with 2,070 FP4 TFLOPS — the highest onboard compute in this comparison. Deployed in retail pharmacies and partnered with Bosch.",
    researchNote:
      "Exceptional compute power makes it ideal for running large VLA models locally. C++/Python SDK available on GitHub. ROS2 integration is not officially confirmed, requiring additional configuration for ROS2-based research workflows.",
    recommendation: "good",
    websiteUrl: "https://www.galbot.com/g1",
  },
  {
    name: "Spirit-AI Moz1",
    manufacturer: "Spirit-AI",
    type: "humanoid",
    country: "China",
    year: 2024,
    heightCm: null,
    heightNote: "Not disclosed",
    weight: null,
    locomotion: "Omnidirectional wheeled base (4-wheel)",
    maxSpeedKmh: null,
    batteryHours: null,
    batteryNote: "Not disclosed",
    ipRating: "IP40",
    priceUsd: "Not disclosed",
    dofTotal: 26,
    dofNote: "~26 DOF (22 body + 4 base)",
    dofHead: 2,
    dofTorso: 6,
    dofArmEach: 7,
    dofBase: "4 DOF omnidirectional",
    payloadPerArm: 5,
    payloadNote: "5 kg per arm",
    cpu: "x86_64 or aarch64 (model not disclosed)",
    gpu: "Inference Host (model not disclosed)",
    memory: "Not disclosed",
    aiCompute: "Not disclosed",
    os: "Ubuntu 22.04",
    sensors: [
      "Intel RealSense D455 (head depth camera)",
      "Intel RealSense D405 ×2 (wrist depth cameras)",
      "Livox MID-360 LiDAR (SLAM)",
      "Two-finger grippers ×2",
    ],
    connectivity: ["Ethernet", "Wi-Fi", "USB 3.2"],
    rosCompatible: 1,
    ros2Support: "native",
    ros2Note:
      "MozRobot SDK is built natively on ROS2 Humble. Requires Ubuntu 22.04, Python 3.10+. Includes robot_interface and mc_core_interface ROS2 packages.",
    sdkAvailable: 1,
    sdkLanguages: ["Python"],
    simulationSupport: ["NVIDIA Isaac Sim", "Google MuJoCo"],
    sdkLinks: [
      { label: "Official Website", url: "https://www.spirit-ai.com/en/", type: "website" },
      { label: "SDK Documentation", url: "https://docs.spirit-ai.com/sdk/get-started.html", type: "docs" },
      { label: "Moz1 Documentation", url: "https://docs.spirit-ai.com/moz1/get-started.html", type: "docs" },
      { label: "Spirit-v1.5 VLA Model (GitHub)", url: "https://github.com/Spirit-AI-Team/spirit-v1.5", type: "github" },
    ],
    llmIntegration: 1,
    openSource: 1,
    aiPlatform: "MozRobot SDK (ROS2 Humble native); Spirit-v1.5 VLA",
    openSourceModel: "Spirit-v1.5 VLA model (open-source on GitHub)",
    scoreSdkOpenness: 5,
    scoreRos2Support: 5,
    scoreComputePower: 3,
    scoreSimulationSupport: 5,
    scoreDeveloperCommunity: 4,
    scorePayloadCapability: 2,
    scoreDexterity: 3,
    scoreResearchOverall: 5,
    summary:
      "Purpose-built for developers and researchers. The MozRobot SDK is natively built on ROS2 Humble, making it the most ROS2-native platform in this comparison. Features Intel RealSense depth cameras, MID-360 LiDAR, and supports NVIDIA Isaac and Google MuJoCo simulation.",
    researchNote:
      "Ideal for teams deeply embedded in the ROS2 ecosystem. Native ROS2 Humble architecture, official Python SDK, and open-source Spirit-v1.5 VLA model provide seamless integration for custom navigation, manipulation, and agentic AI algorithms.",
    recommendation: "top",
    websiteUrl: "https://www.spirit-ai.com/en/",
  },
  {
    name: "Lanxin VB2",
    manufacturer: "Lanxin Robotics",
    type: "humanoid",
    country: "China",
    year: 2024,
    heightCm: 170,
    weight: 70,
    locomotion: "Four-wheel omnidirectional",
    maxSpeedKmh: 7,
    batteryHours: 4,
    batteryNote: "2.5–6 hours depending on load",
    ipRating: null,
    priceUsd: "~$150,000",
    dofTotal: 47,
    dofNote: "47 DOF total",
    dofArmEach: 7,
    dofHandEach: 7,
    dofBase: "Omnidirectional wheels",
    payloadPerArm: 6.5,
    payloadNote: "6.5 kg per arm; 5 kg gripping load",
    cpu: "Industrial PC (model not disclosed)",
    gpu: "AI accelerator (model not disclosed)",
    memory: "Not disclosed",
    aiCompute: "~6 TOPS (reference from VB-1)",
    os: "Linux-based",
    sensors: [
      "Panoramic RGB-D depth vision (270°×70° FOV, 30m range)",
      "360° visual obstacle avoidance (4 cameras)",
      "Dual-lens manipulation camera (±0.1mm precision at 350mm)",
      "Stereo RGB vision",
    ],
    connectivity: ["Ethernet", "Wi-Fi"],
    rosCompatible: 0,
    ros2Support: "not-confirmed",
    ros2Note: "Listed as ROS compatible by third-party sources; no official SDK or ROS2 driver publicly available",
    sdkAvailable: 0,
    sdkLanguages: [],
    simulationSupport: [],
    sdkLinks: [
      { label: "Official Website", url: "https://www.lanxinrobotics.com/humanoid-robots-vb2/", type: "website" },
    ],
    llmIntegration: 0,
    openSource: 0,
    aiPlatform: "Proprietary (not disclosed)",
    openSourceModel: null,
    scoreSdkOpenness: 1,
    scoreRos2Support: 1,
    scoreComputePower: 2,
    scoreSimulationSupport: 1,
    scoreDeveloperCommunity: 1,
    scorePayloadCapability: 4,
    scoreDexterity: 5,
    scoreResearchOverall: 2,
    summary:
      "High-DOF humanoid with 47 degrees of freedom and 5-fingered dexterous hands. Uses pure vision-based navigation (no LiDAR dependency). Targets industrial and logistics applications with a 6.5 kg payload per arm.",
    researchNote:
      "No publicly available SDK, API documentation, or GitHub repository found. Despite impressive hardware specs, the lack of developer tools makes independent software development highly challenging without direct manufacturer engagement.",
    recommendation: "not-recommended",
    websiteUrl: "https://www.lanxinrobotics.com/humanoid-robots-vb2/",
  },
  {
    name: "Realman G4 (RealBOT)",
    manufacturer: "RealMan Robotics",
    type: "humanoid",
    country: "China",
    year: 2024,
    heightCm: 168,
    weight: 95,
    locomotion: "Wheeled base with lifting platform (0–0.95m lift)",
    maxSpeedKmh: null,
    batteryHours: null,
    batteryNote: "~1.65 hour charge time",
    ipRating: "IP54 (arm)",
    priceUsd: "Not disclosed",
    dofTotal: 21,
    dofNote: "21 active DOF",
    dofArmEach: 7,
    dofBase: "Wheeled lifting platform",
    payloadPerArm: 5,
    payloadNote: "5 kg per arm (peak 9 kg); ±0.05mm repeatability",
    cpu: "Not specified",
    gpu: "NVIDIA Jetson Orin (primary) / Digua RDK S100 (alternative)",
    memory: "Not disclosed",
    aiCompute: "Not disclosed",
    os: "Linux",
    sensors: ["Depth cameras", "Wide-angle cameras", "LiDAR", "IMU", "Microphone arrays"],
    connectivity: ["Wi-Fi", "Ethernet", "Bluetooth", "USB", "RS485"],
    rosCompatible: 1,
    ros2Support: "official-driver",
    ros2Note:
      "Official ROS2 driver (ros2_rm_robot) available on GitHub with 158 stars. Also has ROS1 driver (rm_robot). Supports Gazebo, MoveIt, Webots simulation.",
    sdkAvailable: 1,
    sdkLanguages: ["C", "C++", "Python", "JSON"],
    simulationSupport: ["Gazebo", "MoveIt", "Webots"],
    sdkLinks: [
      { label: "Official Website", url: "https://www.realman-robotics.com/", type: "website" },
      { label: "Developer Center", url: "https://develop.realman-robotics.com/en/robot4th/summarize/", type: "docs" },
      { label: "ROS2 Driver (GitHub)", url: "https://github.com/RealManRobot/ros2_rm_robot", type: "github" },
      { label: "ROS1 Driver (GitHub)", url: "https://github.com/RealManRobot/rm_robot", type: "github" },
      { label: "C API — RM_API2 (GitHub)", url: "https://github.com/RealManRobot/RM_API2", type: "github" },
      { label: "URDF Models (GitHub)", url: "https://github.com/RealManRobot/rm_models", type: "github" },
    ],
    llmIntegration: 0,
    openSource: 1,
    aiPlatform: "Open embodied AI platform; RealSource dataset (open-sourced Dec 2025)",
    openSourceModel: "RealSource dataset (open-sourced)",
    scoreSdkOpenness: 4,
    scoreRos2Support: 5,
    scoreComputePower: 4,
    scoreSimulationSupport: 4,
    scoreDeveloperCommunity: 4,
    scorePayloadCapability: 3,
    scoreDexterity: 3,
    scoreResearchOverall: 4,
    summary:
      "RealMan's embodied AI open platform built on their Gen 4 ultra-lightweight 7-DOF arms. Features 21 active DOF, NVIDIA Jetson Orin compute, and the most mature open-source developer ecosystem in this comparison with official ROS1/ROS2 drivers and multiple API languages.",
    researchNote:
      "Excellent for manipulation-focused research. Official ROS2 drivers, C/C++/Python/JSON APIs, and URDF simulation models are all publicly available on GitHub. The open RealSource dataset and teleoperation support make it well-suited for embodied AI research.",
    recommendation: "strong",
    websiteUrl: "https://www.realman-robotics.com/",
  },
  {
    name: "Dexmate Vega",
    manufacturer: "Dexmate Inc.",
    type: "humanoid",
    country: "USA",
    year: 2025,
    heightCm: 171,
    heightNote: "Extends to 220 cm with foldable torso",
    weight: 135,
    locomotion: "Omnidirectional wheeled base",
    maxSpeedKmh: 4,
    batteryHours: 20,
    batteryNote: "10–20+ hours; up to 30 hours without payload",
    ipRating: null,
    priceUsd: "$80,000 – $96,000",
    dofTotal: 36,
    dofNote: "36+ DOF",
    dofHead: 3,
    dofTorso: 3,
    dofArmEach: 7,
    dofHandEach: 6,
    dofBase: "Omnidirectional",
    payloadPerArm: 4.5,
    payloadNote: "4.5 kg per arm (10 lbs; dual-arm 9 kg)",
    cpu: "Intel x86",
    gpu: "NVIDIA Jetson AGX Orin (Jetson Thor coming soon)",
    memory: "Not disclosed",
    aiCompute: "Not disclosed",
    os: "Linux",
    sensors: [
      "RGB-D head camera",
      "LiDAR",
      "Ultrasonic sensors",
      "6-axis force/torque sensor (wrist)",
      "RGB cameras",
      "IMU",
    ],
    connectivity: ["Bluetooth", "Ethernet", "USB 3.2 ×4", "Wi-Fi", "DisplayPort", "5V/12V power rails"],
    rosCompatible: 1,
    ros2Support: "via-bridge",
    ros2Note:
      "ROS/ROS2 compatible via dexcontrol-rosbridge. URDF/USD files available for NVIDIA Isaac Sim and Gazebo. cartographer_ros_vega for SLAM.",
    sdkAvailable: 1,
    sdkLanguages: ["Python"],
    simulationSupport: ["NVIDIA Isaac Sim", "Gazebo"],
    sdkLinks: [
      { label: "Official Website", url: "https://www.dexmate.ai/product/vega", type: "website" },
      { label: "dexcontrol SDK (GitHub)", url: "https://github.com/dexmate-ai/dexcontrol", type: "github" },
      { label: "URDF Models (GitHub)", url: "https://github.com/dexmate-ai/dexmate-urdf", type: "github" },
      { label: "ROS Bridge (GitHub)", url: "https://github.com/dexmate-ai/dexcontrol-rosbridge", type: "github" },
      { label: "Teleoperation (GitHub)", url: "https://github.com/dexmate-ai/omniteleop", type: "github" },
      { label: "Cartographer ROS (GitHub)", url: "https://github.com/dexmate-ai/cartographer_ros_vega", type: "github" },
    ],
    llmIntegration: 1,
    openSource: 1,
    aiPlatform: "dexcontrol Python API; native LLM integration",
    openSourceModel: "AGPL-3.0 open-source SDK (commercial license available)",
    scoreSdkOpenness: 5,
    scoreRos2Support: 4,
    scoreComputePower: 4,
    scoreSimulationSupport: 5,
    scoreDeveloperCommunity: 4,
    scorePayloadCapability: 5,
    scoreDexterity: 5,
    scoreResearchOverall: 5,
    summary:
      "Production-ready US-built humanoid with a high payload and the longest battery life (20+ hours) in this comparison. Features a foldable torso reaching 2.2m, 5-fingered dexterous hands, and a developer-friendly Python API installable via pip.",
    researchNote:
      "Best choice for ease of development and high-payload manipulation research. `pip install dexcontrol` provides immediate access, with native LLM integration, NVIDIA Isaac Sim support, and comprehensive simulation assets. Research grant program available via Vega U.",
    recommendation: "top",
    websiteUrl: "https://www.dexmate.ai/product/vega",
  },
];

async function seedDatabase() {
  console.log("Starting database seeding (idempotent: replaces rows by name)...");

  try {
    for (const robot of sampleRobots) {
      // Idempotency: remove any existing rows with this name (collapses
      // duplicates from previous runs), then insert a single fresh copy.
      const removed = await db.delete(robots).where(eq(robots.name, robot.name));
      const dupCount = Number(removed[0]?.affectedRows ?? 0);
      await db.insert(robots).values(robot);
      console.log(`✓ ${dupCount > 0 ? `Replaced (${dupCount} existing)` : "Added"}: ${robot.name}`);
    }

    console.log("\n✅ Database seeded successfully!");
    console.log(`Total seed robots: ${sampleRobots.length} (re-running this script is now safe)`);
  } catch (error) {
    console.error("❌ Error seeding database:", error);
    process.exit(1);
  }

  process.exit(0);
}

seedDatabase();
